name: render site

on: 
  workflow_dispatch:
  push:

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          node sync-doc.shell.js
          npm run build
          npm run export
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./out/**/*
          name: site